export type JobType = "Full-time" | "Part-time" | "Contract" | "Freelance";
export type WorkMode = "Remote" | "Hybrid" | "Onsite";

export interface Category {
  id: string;
  name: string;
  slug: string;
}

export interface Location {
  id: string;
  city: string;
  country: string;
  region: string;
}

export interface Job {
  id: string;
  title: string;
  companyId: string;
  categoryId: string;
  locationId: string;
  jobType: JobType;
  remote: WorkMode;
  salary: string;
  source: string;
  url: string;
  lastUpdated: string;
}

export interface Company {
  id: string;
  name: string;
  slug: string;
  description: string;
  logo: string;
  website: string;
  jobs: string[];
  updatedAt: string;
  source: string;
}

export const categories: Category[] = [
  { id: "ai-training", name: "AI Training", slug: "ai-training" },
  { id: "prompt-engineering", name: "Prompt Engineering", slug: "prompt-engineering" },
  { id: "data-annotation", name: "Data Annotation", slug: "data-annotation" },
  { id: "llm-evaluation", name: "LLM Evaluation", slug: "llm-evaluation" },
  { id: "ml-engineering", name: "ML Engineering", slug: "ml-engineering" },
  { id: "software-engineering", name: "Software Engineering", slug: "software-engineering" },
];

export const locations: Location[] = [
  { id: "us-remote", city: "Remote", country: "United States", region: "North America" },
  { id: "ca-remote", city: "Remote", country: "Canada", region: "North America" },
  { id: "uk-remote", city: "Remote", country: "United Kingdom", region: "Europe" },
  { id: "de-berlin", city: "Berlin", country: "Germany", region: "Europe" },
  { id: "in-remote", city: "Remote", country: "India", region: "Asia" },
  { id: "sg-remote", city: "Remote", country: "Singapore", region: "Asia" },
  { id: "au-remote", city: "Remote", country: "Australia", region: "Oceania" },
  { id: "br-remote", city: "Remote", country: "Brazil", region: "South America" },
];

export const companies: Company[] = [
  {
    id: "mercor",
    name: "Mercor",
    slug: "mercor",
    description: "AI staffing platform connecting talent with frontier model builders.",
    logo: "M",
    website: "https://mercor.com",
    jobs: ["mercor-1", "mercor-2"],
    updatedAt: "2026-07-16",
    source: "Company Careers"
  },
  {
    id: "outlier",
    name: "Outlier",
    slug: "outlier",
    description: "Flexible AI training and evaluation opportunities for specialists worldwide.",
    logo: "O",
    website: "https://outlier.ai",
    jobs: ["outlier-1"],
    updatedAt: "2026-07-14",
    source: "Company Careers"
  },
  {
    id: "telus-digital",
    name: "TELUS Digital",
    slug: "telus-digital",
    description: "Global digital customer experience and data operations company.",
    logo: "TD",
    website: "https://www.telusinternational.com",
    jobs: ["telus-1", "telus-2"],
    updatedAt: "2026-07-12",
    source: "Company Careers"
  },
  {
    id: "invisible",
    name: "Invisible Technologies",
    slug: "invisible-technologies",
    description: "Human-in-the-loop AI infrastructure for enterprise copilots and automation.",
    logo: "I",
    website: "https://www.invisible.email",
    jobs: ["invisible-1"],
    updatedAt: "2026-07-11",
    source: "Company Careers"
  },
  {
    id: "scale-ai",
    name: "Scale AI",
    slug: "scale-ai",
    description: "Data and model evaluation at the core of modern applied AI systems.",
    logo: "S",
    website: "https://scale.com",
    jobs: ["scale-1", "scale-2"],
    updatedAt: "2026-07-10",
    source: "Company Careers"
  },
  {
    id: "rws",
    name: "RWS",
    slug: "rws",
    description: "Language data and AI training services for global language technology.",
    logo: "R",
    website: "https://www.rws.com",
    jobs: ["rws-1"],
    updatedAt: "2026-07-09",
    source: "Company Careers"
  },
  {
    id: "oneforma",
    name: "OneForma",
    slug: "oneforma",
    description: "Crowdsourced data annotation and linguistic AI support work.",
    logo: "OF",
    website: "https://www.oneforma.com",
    jobs: ["oneforma-1"],
    updatedAt: "2026-07-08",
    source: "Company Careers"
  },
  {
    id: "welocalize",
    name: "Welocalize",
    slug: "welocalize",
    description: "Localization and data services powering multilingual AI products.",
    logo: "W",
    website: "https://www.welocalize.com",
    jobs: ["welocalize-1"],
    updatedAt: "2026-07-07",
    source: "Company Careers"
  },
  {
    id: "dataforce",
    name: "DataForce",
    slug: "dataforce",
    description: "High-volume data collection and AI model support for global clients.",
    logo: "DF",
    website: "https://www.dataforce.ai",
    jobs: ["dataforce-1"],
    updatedAt: "2026-07-06",
    source: "Company Careers"
  },
  {
    id: "appen",
    name: "Appen",
    slug: "appen",
    description: "Datasets and human feedback powering the next generation of AI systems.",
    logo: "A",
    website: "https://appen.com",
    jobs: ["appen-1"],
    updatedAt: "2026-07-05",
    source: "Company Careers"
  },
  {
    id: "alignerr",
    name: "Alignerr",
    slug: "alignerr",
    description: "Specialist platform for model alignment and AI training projects.",
    logo: "AL",
    website: "https://alignerr.com",
    jobs: ["alignerr-1"],
    updatedAt: "2026-07-04",
    source: "Company Careers"
  },
  {
    id: "turing",
    name: "Turing",
    slug: "turing",
    description: "Remote engineering talent network with AI and software opportunities.",
    logo: "T",
    website: "https://turing.com",
    jobs: ["turing-1"],
    updatedAt: "2026-07-03",
    source: "Company Careers"
  },
  {
    id: "surge-ai",
    name: "Surge AI",
    slug: "surge-ai",
    description: "Human feedback and data collection for AI model quality improvement.",
    logo: "SA",
    website: "https://surge.ai",
    jobs: ["surge-1"],
    updatedAt: "2026-07-02",
    source: "Company Careers"
  },
  {
    id: "xai",
    name: "xAI",
    slug: "xai",
    description: "Building advanced AI systems for research and product deployment.",
    logo: "X",
    website: "https://x.ai",
    jobs: ["xai-1"],
    updatedAt: "2026-07-01",
    source: "Company Careers"
  },
  {
    id: "openai",
    name: "OpenAI",
    slug: "openai",
    description: "Research and product roles building the future of general-purpose AI.",
    logo: "OA",
    website: "https://openai.com",
    jobs: ["openai-1"],
    updatedAt: "2026-06-30",
    source: "Company Careers"
  },
  {
    id: "anthropic",
    name: "Anthropic",
    slug: "anthropic",
    description: "Safety-first AI company with research and engineering openings globally.",
    logo: "AN",
    website: "https://www.anthropic.com",
    jobs: ["anthropic-1"],
    updatedAt: "2026-06-29",
    source: "Company Careers"
  },
  {
    id: "google-deepmind",
    name: "Google DeepMind",
    slug: "google-deepmind",
    description: "Cutting-edge AI research and applied engineering opportunities.",
    logo: "GD",
    website: "https://deepmind.google",
    jobs: ["deepmind-1"],
    updatedAt: "2026-06-28",
    source: "Company Careers"
  },
  {
    id: "microsoft-ai",
    name: "Microsoft AI",
    slug: "microsoft-ai",
    description: "Applied AI and platform roles across the Azure and Copilot ecosystem.",
    logo: "MS",
    website: "https://careers.microsoft.com",
    jobs: ["microsoft-1"],
    updatedAt: "2026-06-27",
    source: "Company Careers"
  },
  {
    id: "amazon-ai",
    name: "Amazon AI",
    slug: "amazon-ai",
    description: "Large-scale AI and machine learning roles across AWS and consumer products.",
    logo: "AM",
    website: "https://www.amazon.jobs",
    jobs: ["amazon-1"],
    updatedAt: "2026-06-26",
    source: "Company Careers"
  },
  {
    id: "meta-ai",
    name: "Meta AI",
    slug: "meta-ai",
    description: "AI research and engineering roles shaping the next generation of products.",
    logo: "M2",
    website: "https://www.metacareers.com",
    jobs: ["meta-1"],
    updatedAt: "2026-06-25",
    source: "Company Careers"
  },
  {
    id: "nvidia",
    name: "NVIDIA",
    slug: "nvidia",
    description: "Accelerated computing and AI platform roles for ambitious builders.",
    logo: "NV",
    website: "https://www.nvidia.com",
    jobs: ["nvidia-1"],
    updatedAt: "2026-06-24",
    source: "Company Careers"
  },
  {
    id: "cohere",
    name: "Cohere",
    slug: "cohere",
    description: "Enterprise AI research and applied model development roles.",
    logo: "C",
    website: "https://cohere.com",
    jobs: ["cohere-1"],
    updatedAt: "2026-06-23",
    source: "Company Careers"
  },
  {
    id: "mistral",
    name: "Mistral AI",
    slug: "mistral-ai",
    description: "Open-weight AI model company with research and product roles worldwide.",
    logo: "MA",
    website: "https://mistral.ai",
    jobs: ["mistral-1"],
    updatedAt: "2026-06-22",
    source: "Company Careers"
  },
  {
    id: "perplexity",
    name: "Perplexity",
    slug: "perplexity",
    description: "Search and AI assistant teams building intelligent knowledge experiences.",
    logo: "P",
    website: "https://www.perplexity.ai",
    jobs: ["perplexity-1"],
    updatedAt: "2026-06-21",
    source: "Company Careers"
  },
];

export const jobs: Job[] = [
  {
    id: "mercor-1",
    title: "AI Data Labeling Specialist",
    companyId: "mercor",
    categoryId: "data-annotation",
    locationId: "us-remote",
    jobType: "Contract",
    remote: "Remote",
    salary: "$35-$55/hr",
    source: "Mercor Careers",
    url: "https://mercor.com/careers",
    lastUpdated: "2026-07-16",
  },
  {
    id: "mercor-2",
    title: "Prompt Evaluator",
    companyId: "mercor",
    categoryId: "llm-evaluation",
    locationId: "ca-remote",
    jobType: "Freelance",
    remote: "Remote",
    salary: "$30-$45/hr",
    source: "Mercor Careers",
    url: "https://mercor.com/careers",
    lastUpdated: "2026-07-15",
  },
  {
    id: "outlier-1",
    title: "AI Training Expert",
    companyId: "outlier",
    categoryId: "ai-training",
    locationId: "uk-remote",
    jobType: "Part-time",
    remote: "Remote",
    salary: "$20-$40/hr",
    source: "Outlier Careers",
    url: "https://outlier.ai/careers",
    lastUpdated: "2026-07-14",
  },
  {
    id: "telus-1",
    title: "Search Quality Rater",
    companyId: "telus-digital",
    categoryId: "llm-evaluation",
    locationId: "us-remote",
    jobType: "Full-time",
    remote: "Hybrid",
    salary: "$18-$28/hr",
    source: "TELUS Digital",
    url: "https://www.telusinternational.com/careers",
    lastUpdated: "2026-07-12",
  },
  {
    id: "telus-2",
    title: "AI Content Reviewer",
    companyId: "telus-digital",
    categoryId: "data-annotation",
    locationId: "de-berlin",
    jobType: "Contract",
    remote: "Onsite",
    salary: "$22-$30/hr",
    source: "TELUS Digital",
    url: "https://www.telusinternational.com/careers",
    lastUpdated: "2026-07-11",
  },
  {
    id: "invisible-1",
    title: "AI Data Operations Specialist",
    companyId: "invisible",
    categoryId: "software-engineering",
    locationId: "us-remote",
    jobType: "Full-time",
    remote: "Remote",
    salary: "$90k-$140k",
    source: "Invisible Technologies",
    url: "https://www.invisible.email/careers",
    lastUpdated: "2026-07-11",
  },
  {
    id: "scale-1",
    title: "ML Data Operations Engineer",
    companyId: "scale-ai",
    categoryId: "ml-engineering",
    locationId: "us-remote",
    jobType: "Full-time",
    remote: "Remote",
    salary: "$120k-$180k",
    source: "Scale AI Careers",
    url: "https://scale.com/careers",
    lastUpdated: "2026-07-10",
  },
  {
    id: "scale-2",
    title: "AI Safety Evaluator",
    companyId: "scale-ai",
    categoryId: "llm-evaluation",
    locationId: "in-remote",
    jobType: "Contract",
    remote: "Remote",
    salary: "$25-$45/hr",
    source: "Scale AI Careers",
    url: "https://scale.com/careers",
    lastUpdated: "2026-07-09",
  },
  {
    id: "rws-1",
    title: "Language AI Specialist",
    companyId: "rws",
    categoryId: "ai-training",
    locationId: "sg-remote",
    jobType: "Freelance",
    remote: "Remote",
    salary: "$20-$35/hr",
    source: "RWS Careers",
    url: "https://www.rws.com/careers",
    lastUpdated: "2026-07-09",
  },
  {
    id: "oneforma-1",
    title: "Data Annotator",
    companyId: "oneforma",
    categoryId: "data-annotation",
    locationId: "br-remote",
    jobType: "Part-time",
    remote: "Remote",
    salary: "$12-$22/hr",
    source: "OneForma Careers",
    url: "https://www.oneforma.com/careers",
    lastUpdated: "2026-07-08",
  },
  {
    id: "welocalize-1",
    title: "Localization Data QA Specialist",
    companyId: "welocalize",
    categoryId: "llm-evaluation",
    locationId: "au-remote",
    jobType: "Contract",
    remote: "Hybrid",
    salary: "$24-$38/hr",
    source: "Welocalize Careers",
    url: "https://www.welocalize.com/careers",
    lastUpdated: "2026-07-07",
  },
  {
    id: "dataforce-1",
    title: "AI Training Analyst",
    companyId: "dataforce",
    categoryId: "ai-training",
    locationId: "us-remote",
    jobType: "Full-time",
    remote: "Remote",
    salary: "$60k-$95k",
    source: "DataForce Careers",
    url: "https://www.dataforce.ai/careers",
    lastUpdated: "2026-07-06",
  },
  {
    id: "appen-1",
    title: "AI Data Contributor",
    companyId: "appen",
    categoryId: "data-annotation",
    locationId: "ca-remote",
    jobType: "Part-time",
    remote: "Remote",
    salary: "$18-$30/hr",
    source: "Appen Careers",
    url: "https://appen.com/careers",
    lastUpdated: "2026-07-05",
  },
  {
    id: "alignerr-1",
    title: "Model Alignment Specialist",
    companyId: "alignerr",
    categoryId: "prompt-engineering",
    locationId: "uk-remote",
    jobType: "Freelance",
    remote: "Remote",
    salary: "$25-$45/hr",
    source: "Alignerr Careers",
    url: "https://alignerr.com/careers",
    lastUpdated: "2026-07-04",
  },
  {
    id: "turing-1",
    title: "Software Engineer, AI Platform",
    companyId: "turing",
    categoryId: "software-engineering",
    locationId: "us-remote",
    jobType: "Full-time",
    remote: "Remote",
    salary: "$110k-$160k",
    source: "Turing Careers",
    url: "https://turing.com/careers",
    lastUpdated: "2026-07-03",
  },
  {
    id: "surge-1",
    title: "LLM Evaluation Annotator",
    companyId: "surge-ai",
    categoryId: "llm-evaluation",
    locationId: "in-remote",
    jobType: "Contract",
    remote: "Remote",
    salary: "$18-$30/hr",
    source: "Surge AI Careers",
    url: "https://surge.ai/careers",
    lastUpdated: "2026-07-02",
  },
  {
    id: "xai-1",
    title: "Research Engineer",
    companyId: "xai",
    categoryId: "ml-engineering",
    locationId: "us-remote",
    jobType: "Full-time",
    remote: "Hybrid",
    salary: "$165k-$240k",
    source: "xAI Careers",
    url: "https://x.ai/careers",
    lastUpdated: "2026-07-01",
  },
  {
    id: "openai-1",
    title: "Applied AI Engineer",
    companyId: "openai",
    categoryId: "software-engineering",
    locationId: "us-remote",
    jobType: "Full-time",
    remote: "Remote",
    salary: "$180k-$280k",
    source: "OpenAI Careers",
    url: "https://openai.com/careers",
    lastUpdated: "2026-06-30",
  },
  {
    id: "anthropic-1",
    title: "Safety Research Engineer",
    companyId: "anthropic",
    categoryId: "ml-engineering",
    locationId: "uk-remote",
    jobType: "Full-time",
    remote: "Remote",
    salary: "$190k-$270k",
    source: "Anthropic Careers",
    url: "https://www.anthropic.com/careers",
    lastUpdated: "2026-06-29",
  },
  {
    id: "deepmind-1",
    title: "AI Research Scientist",
    companyId: "google-deepmind",
    categoryId: "ml-engineering",
    locationId: "uk-remote",
    jobType: "Full-time",
    remote: "Remote",
    salary: "$180k-$260k",
    source: "Google DeepMind Careers",
    url: "https://deepmind.google/careers",
    lastUpdated: "2026-06-28",
  },
  {
    id: "microsoft-1",
    title: "Applied Scientist, AI Platform",
    companyId: "microsoft-ai",
    categoryId: "software-engineering",
    locationId: "us-remote",
    jobType: "Full-time",
    remote: "Hybrid",
    salary: "$150k-$230k",
    source: "Microsoft AI Careers",
    url: "https://careers.microsoft.com",
    lastUpdated: "2026-06-27",
  },
  {
    id: "amazon-1",
    title: "Machine Learning Engineer",
    companyId: "amazon-ai",
    categoryId: "ml-engineering",
    locationId: "us-remote",
    jobType: "Full-time",
    remote: "Remote",
    salary: "$140k-$220k",
    source: "Amazon AI Careers",
    url: "https://www.amazon.jobs",
    lastUpdated: "2026-06-26",
  },
  {
    id: "meta-1",
    title: "Research Engineer, AI Systems",
    companyId: "meta-ai",
    categoryId: "software-engineering",
    locationId: "us-remote",
    jobType: "Full-time",
    remote: "Remote",
    salary: "$170k-$260k",
    source: "Meta AI Careers",
    url: "https://www.metacareers.com",
    lastUpdated: "2026-06-25",
  },
  {
    id: "nvidia-1",
    title: "Systems Software Engineer",
    companyId: "nvidia",
    categoryId: "software-engineering",
    locationId: "au-remote",
    jobType: "Full-time",
    remote: "Remote",
    salary: "$140k-$220k",
    source: "NVIDIA Careers",
    url: "https://www.nvidia.com/en-us/about-nvidia/careers",
    lastUpdated: "2026-06-24",
  },
  {
    id: "cohere-1",
    title: "Applied AI Researcher",
    companyId: "cohere",
    categoryId: "ml-engineering",
    locationId: "ca-remote",
    jobType: "Full-time",
    remote: "Hybrid",
    salary: "$160k-$240k",
    source: "Cohere Careers",
    url: "https://cohere.com/careers",
    lastUpdated: "2026-06-23",
  },
  {
    id: "mistral-1",
    title: "LLM Platform Engineer",
    companyId: "mistral",
    categoryId: "software-engineering",
    locationId: "de-berlin",
    jobType: "Full-time",
    remote: "Remote",
    salary: "$140k-$220k",
    source: "Mistral AI Careers",
    url: "https://mistral.ai/careers",
    lastUpdated: "2026-06-22",
  },
  {
    id: "perplexity-1",
    title: "Search AI Engineer",
    companyId: "perplexity",
    categoryId: "software-engineering",
    locationId: "us-remote",
    jobType: "Full-time",
    remote: "Remote",
    salary: "$165k-$245k",
    source: "Perplexity Careers",
    url: "https://www.perplexity.ai/careers",
    lastUpdated: "2026-06-21",
  },
];
