import { Router, type IRouter } from "express";
import healthRouter from "./health";
import toolsRouter from "./tools";
import blogRouter from "./blog";
import faqRouter from "./faq";
import contactRouter from "./contact";
import mergeRouter from "./merge";
import splitRouter from "./split";
import imageRouter from "./image";
import officeRouter from "./office";
import ocrRouter from "./ocr";
import organizeRouter from "./organize";
import deletePagesRouter from "./delete-pages";
import extractPagesRouter from "./extract-pages";
import pdfAnnotationsRouter from "./pdf-annotations-route";
import adminRouter from "./admin";
import aiJobsRouter from "./ai-jobs";
import downloadPdfRouter from "./download-pdf";
import searchPdfsRouter from "./search-pdfs";

const router: IRouter = Router();

router.use(healthRouter);
router.use(toolsRouter);
router.use(blogRouter);
router.use(faqRouter);
router.use(contactRouter);
router.use(mergeRouter);
router.use(splitRouter);
router.use(imageRouter);
router.use(officeRouter);
router.use(ocrRouter);
router.use(organizeRouter);
router.use(deletePagesRouter);
router.use(extractPagesRouter);
router.use(pdfAnnotationsRouter);
router.use(adminRouter);
router.use(aiJobsRouter);
router.use(downloadPdfRouter);
router.use(searchPdfsRouter);

export default router;
